name: bms

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    command: server
    ports:
      - 8200:8200
    volumes:
      - vault:/vault/file
      - ./vault:/vault/config
  api.bms:
    depends_on:
      - vault
      - pg.bms
      - prom.bms
    image: dev/bms-server:$SERVER_VERSION
    build:
      context: ./bms-server
      target: application
      args:
        VERSION: $SERVER_VERSION
    volumes:
      - ./certs:/bms/certs
      - ./logs:/bms/logs
    environment:
      - CERTS_DIR=/bms/certs/server
      - SSL_CERT_PATH=server.crt
      - SSL_KEY_PATH=server.key
      - SSL_CA_PATH=ca.crt
    env_file: .env.server.docker
  pg.bms:
    image: postgres:17-alpine
    command: -c ssl=true -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./certs/pg/server.crt:/var/lib/postgresql/server.crt
      - ./certs/pg/server.key:/var/lib/postgresql/server.key
    env_file: .env.pg.docker
  prom.bms:
    image: prom/prometheus:v3.1.0
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prom/config.yml:/etc/prometheus/prometheus.yml

volumes:
  prometheus:
  vault:
  db:
