
name: bms

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    command: server
    ports:
      - 8200:8200
    volumes:
      - vault:/vault/file
      - ./vault:/vault/config

volumes:
  vault:
